apiVersion: v1
kind: Pod
metadata:
  name: "sender-{{.Values.name}}"
  labels:
    purpose: demonstrate-send-microservice
    app: sender-{{.Values.name}}
spec:
  containers:
  - name: wormholesender    
    image: jakkaj/wormhole_sender:5
    env:
    - name: RECEIVER_URI
      {{if contains "sender" (index .Values.relationships.output 0).name }}
      value: "http://{{ (index .Values.relationships.output 0).name }}:8080/api/CallReceiver"
      {{else}}
      value: "http://{{ (index .Values.relationships.output 0).name }}:8080/api/EchoBody"
      {{end}}
    - name: CHAIN_ARG
      value: "-Chain-{{.Values.name}}"      
      