version: '3'
services:
  docker-in-docker:
    network_mode: "host"
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace
      # Mount go mod cache
      - abstrakt-gomodcache:/go/pkg
      # Cache vscode exentsions installs and homedir
      - abstrakt-vscodecache:/root/.vscode-server
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro # does not work on Windows! Will need to generate in container :(
      # Forwarding the socket is optional, but lets docker work inside the container if you install the Docker CLI.
      # See the docker-in-docker-compose definition for details on how to install it.
      - /var/run/docker.sock:/var/run/docker.sock
    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity

volumes:
  abstrakt-vscodecache:
  abstrakt-gomodcache:
