apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.name}}"
spec:
  selector:
    app: "receiver-{{.Values.name}}"
  #type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    #nodePort: 31610
    